### ISSUE TITLE
Create release v0.0.1

### ISSUE THREAD

**Issue by favoyang** [JonasDeM/EntitySelection#3]
Hi @JonasDeM ,

Thanks for creating the awesome package. Would please create a github release `v0.0.1`? So the package can be included in upcoming openupm registry ([sneak preview](https://openupm.com)), which is a service that build package directly from git tags that conform semver.

**Comment by JonasDeM** [comment]
My sincere apologies for not responding quicker! I forgot to look into it.
I simply made an alpha release. Will OpenUPM find it now?

**Comment by favoyang** [comment]
@JonasDeM thanks for replying me! the release name (git tag) is not matched with the package.json.

package.json: 0.0.1
git tag: v0.1-alpha

So either you rename/recreate the git tag to `0.0.1`/`v0.0.1` or update the package.json version.

Notice that unity only support `preview` label. So if you insist on using label, that should be `0.0.1-preview`

**Comment by JonasDeM** [comment]
I changed the git tag to v0.0.1 
Let me know if something still needs to be changed, if not i will close this issue.

**Comment by favoyang** [comment]
@JonasDeM thanks for the efforts.

The 0.0.1 version has been processed correctly, so does future releases.
https://openupm.com/packages/io.github.jonasdem.entityselection/

I created PR https://github.com/JonasDeM/EntitySelection/pull/4 for update README and badge.

**Comment by JonasDeM** [comment]
Accepted the PR, good luck with the UPM project!
